apiVersion: skaffold/v4beta4
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: danielfr9/client
      context: client
      sync:
        manual:
          - src: "src/**/*.{js,ts,jsx,tsx,vue}"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: danielfr9/comments
      context: comments
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: danielfr9/event-bus
      context: event-bus
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: danielfr9/moderation
      context: moderation
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: danielfr9/posts
      context: posts
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: danielfr9/query
      context: query
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
